version: "3"
services:

  rancher:
    image: rancher/rancher-agent:v2.3.5
    container_name: rancher
    ports:
      - 8443:443
    user: "104"
    environment: 
      ETCD: "true"
      WORKER: "true"
      CONTROL: "true"
      CATTLE_TOKEN: "fn5nspqrr8cxwc7jgd7zwzct7zmd8vhs7r2qp4z9tznfqg9qbl9mxd" 
      CATTLE_SERVER: "http://localhost:8443"
      CATTLE_CA_CHECKSUM: "c4718aa417bf3ff9e7e09be5f80455a7b1960ca31ab8dd2ff20f95767469fca9" 

  wordpress:
    image: wordpress:latest
    restart: always
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress

  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: somewordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress

volumes:
  db_data: {}
  